version: "1.1"

on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: erda-operator
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.erda-operator }}
  - stage:
      - custom-script:
          alias: build-erda-operator
          commands:
            - cd ${{ dirs.erda-operator }}
            - docker login ${{ configs.docker_registry }} -u ${{ configs.docker_registry_username }} -p ${{ configs.docker_registry_password }}
            - REGISTRY=${{ configs.docker_registry }} IMAGE_TAG=${{ outputs.extract-repo-version.image_tag }} make docker-version-latest
          resources:
            cpu: 2
            mem: 2048