# permissions for end users to view erdas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: erda-viewer-role
rules:
- apiGroups:
  - erda.erda.cloud
  resources:
  - erdas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - erda.erda.cloud
  resources:
  - erdas/status
  verbs:
  - get
